---
# tasks file for firewall_proxmox

- name: Extraer el hostname del inventory_hostname que es el fqdn
  set_fact:
    proxmox_hostname: "{{ inventory_hostname.split('.')[0] }}"


## Verify that python-pip is installed in the proxmox node
- name: Verificar si python-pip está instalado en el nodo proxmox
  apt:
    name: python-pip
    state: present
  delegate_to: "{{ api_host }}"


## Verify if proxmoxer pip module is installed
- name: Verificar si el módulo proxmoxer de python está instalado
  pip:
    name: proxmoxer
    state: present
  delegate_to: "{{ api_host }}"


## Get the VM ID
- name: Extraer el número de VM
  shell: pct list | grep -w "{{ proxmox_hostname }}" | cut -f 1 -d ' '
  delegate_to: "{{ api_host }}"
  register: VMID


## Ensure the existence of the firewall configuration file for the CLUSTER
- name: Asegurar existencia del archivo de configuración de firewall para el CLUSTER
  file:
    path: "/etc/pve/firewall/cluster.fw"
    state: touch
    owner: root
    group: www-data
    mode: "0640"
  delegate_to: "{{ api_host }}"
  when: firewall_proxmox_configure_cluster

## Copy firewall configuration file for the CLUSTER (Called "Datacenter" in Proxmox web panel)
- name: Copiar archivo de configuración de firewall para el CLUSTER (Llamado "Datacenter" en panel web de Proxmox)
  copy:
    src: "{{ firewall_proxmox_files }}/cluster.fw"
    dest: "/etc/pve/firewall/cluster.fw"
    owner: root
    group: www-data
    mode: "0640"
  notify:
    - reload pve-firewall
  delegate_to: "{{ api_host }}"
  when: firewall_proxmox_configure_cluster


## Check if there is a firewall file defined for the container in our project
- name: Comprobar si existe un archivo de firewall definido para el contenedor en nuestro proyecto
  become: no
  local_action: stat path={{ local_path_to_lxc_firewall_file }}
  register: host_firewall_file


## Ensure existence of the firewall configuration file for the container
- name: Asegurar existencia del archivo de configuración de firewall para el contenedor
  file:
    path: "/etc/pve/firewall/{{ VMID.stdout }}.fw"
    state: touch
    owner: root
    group: www-data
    mode: "0640"
  delegate_to: "{{ api_host }}"

## Set firewall configuration file for the container if it is defined
- name: Set archivo de configuración de firewall para el contenedor si está definido
  copy:
    src: "{{ firewall_proxmox_lxc_file }}"
    dest: "/etc/pve/firewall/{{ VMID.stdout }}.fw"
    owner: root
    group: www-data
    mode: "0640"
  notify:
    - reload pve-firewall
  delegate_to: "{{ api_host }}"
  when: host_firewall_file.stat.exists

## Set default firewall file for the container without definition
- name: Set archivo por defecto de firewall para el contenedor sin definición
  copy:
    src: "{{ firewall_proxmox_files }}/default.fw"
    dest: "/etc/pve/firewall/{{ VMID.stdout }}.fw"
    owner: root
    group: www-data
    mode: "0640"
  notify:
    - reload pve-firewall
  delegate_to: "{{ api_host }}"
  when: (not host_firewall_file.stat.exists)